name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/main.svg
          config_timezone: Asia/Bangkok
          user: Planxnx
          template: classic
          base: header, activity, repositories
      - name: Most Used Languages Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.languages.used.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Thanee Charattrakool, Planxnx, planxnx@users.noreply.github.com, planxthanee@gmail.com
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: no
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, lines
          # plugin_languages_ignored: php
      - name: Achivements Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.achivements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_ignored: forker, follower, influencer, gister, worker, explorer, infographile
      - name: Interesting Facts Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.habits.facts.svg
          config_timezone: Asia/Bangkok
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_from: 1000
      - name: Activity Facts Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.habits.charts.svg
          config_timezone: Asia/Bangkok
          base: ""
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          plugin_habits_trim: yes
      # - name: Wakatime Metrics
      #   uses: ./.github/workflows/metrics.wakatime.yml
