name: Most Used Metrics
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.most.used.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Most Used Programing Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/most_used/programing.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Thanee Charattrakool, Planxnx, planxnx@users.noreply.github.com, planxthanee@gmail.com
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: no
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, lines, bytes-size
          # plugin_languages_ignored: php
          plugin_languages_categories: programming
      - name: Most Used Markup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/most_used/markup.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Thanee Charattrakool, Planxnx, planxnx@users.noreply.github.com, planxthanee@gmail.com
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: no
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, lines, bytes-size
          plugin_languages_categories: markup
      - name: Most Used Data Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/most_used/data.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Thanee Charattrakool, Planxnx, planxnx@users.noreply.github.com, planxthanee@gmail.com
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: no
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, lines, bytes-size
          plugin_languages_categories: data
      - name: Most Used Prose Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/most_used/prose.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Thanee Charattrakool, Planxnx, planxnx@users.noreply.github.com, planxthanee@gmail.com
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: no
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, lines, bytes-size
          plugin_languages_categories: prose
