name: Metrics Main
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
    inputs:
      commit_message:
        description: "Commit message"
        default: "chore: update metrics"
      git_user:
        description: "Git user"
        default: "Planxnx"
  push:
    paths:
      - ".github/workflows/metrics.main.yml"
env:
  COMMIT_EMAIL: planxthanee@gmail.com
  COMMIT_USER: Planxnx
  COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
  GIT_USER: ${{ github.event.inputs.git_user || 'Planxnx' }}

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    env:
      METRICS_DIR: "metrics"
      METRICS_FILE_NAME: "main.svg"

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          committer_token: ${{ secrets.GH_TOKEN }}
          filename: ${{ env.METRICS_FILE_NAME }}
          config_timezone: Asia/Bangkok
          user: ${{ env.GIT_USER }}
          template: classic
          base: header, activity, repositories
          # output_action: none

      # - name: Commit Output
      #   run: |
      #     set +e
      #     git config user.name ${{ env.COMMIT_USER }}
      #     git config user.email ${{ env.COMMIT_EMAIL }}
      #     sudo mv /metrics_renders/* /${{ env.METRICS_DIR }}
      #     git add --all
      #     git commit -m "${{ env.COMMIT_MESSAGE }}"
      #     git push
