name: Most Used Languages Metrics
on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
    inputs:
      commit_message:
        description: "Commit message"
        default: "chore: update metrics"
      git_user:
        description: "Git user"
        default: "Planxnx"
  push:
    paths:
      - ".github/workflows/metrics.language.yml"
env:
  COMMIT_EMAIL: planxthanee@gmail.com
  COMMIT_USER: Planxnx
  COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
  GIT_USER: ${{ github.event.inputs.git_user || 'Planxnx' }}

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    env:
      METRICS_DIR: "metrics"
      METRICS_FILE_NAME: "plugin.languages.used.svg"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: ${{ env.METRICS_FILE_NAME }}
          base: ""
          #Readmore: https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Thanee Charattrakool, Planxnx, planxnx@users.noreply.github.com, planxthanee@gmail.com
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: no
          plugin_languages_categories: programming, markup
          plugin_languages_recent_categories: programming, markup
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, lines
          plugin_languages_ignored: hack, php
          output_action: none

      - name: Commit Output
        run: |
          set +e
          git config user.name ${{ env.COMMIT_USER }}
          git config user.email ${{ env.COMMIT_EMAIL }}
          sudo mv /metrics_renders/* /${{ env.METRICS_DIR }}
          git add --all
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push
