name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.name "Planxnx"
          git config --global user.email "planxthanee@gmail.com"
      - name: Main Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/main.svg
          config_timezone: Asia/Bangkok
          user: Planxnx
          template: classic
          base: header, activity, repositories
      - name: Achivements Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.achivements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_ignored: forker, follower, influencer, gister, worker, explorer, infographile
      - name: Interesting Facts Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.habits.facts.svg
          config_timezone: Asia/Bangkok
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_from: 1000
      - name: Activity Facts Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.habits.charts.svg
          config_timezone: Asia/Bangkok
          base: ""
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          plugin_habits_trim: yes
      # - name: Wakatime Metrics
      #   uses: ./.github/workflows/metrics.wakatime.yml
      # - name: Most Used Languages Metrics
      #   uses: ./.github/workflows/metrics.language.yml
