name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Main Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.main.svg
          # Options
          user: Planxnx
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Bangkok
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 14
          plugin_wakatime_limit: 5
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, os
          plugin_wakatime_url: https://wakatime.com
      - name: Used Languages Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.plugin.languages.used.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Thanee Charattrakool, Planxnx, planxnx@users.noreply.github.com, planxthanee@gmail.com
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 400
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage
          plugin_languages_ignored: php, hack
