name: Metrics Achivements
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.starlists.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Star Lists Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.starlists.svg
          base: ""
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 10
          # plugin_starlists_languages_ignored:
          # plugin_starlists_languages_aliases:
