name: Metrics Achivements
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.achivements.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Achivements Metrics
        uses: lowlighter/metrics@master # use @master to test new features, See more: https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md#3%EF%B8%8F1%EF%B8%8F-choosing-between-latest-mastermain-a-fork-or-a-pinned-version
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.achivements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          debug_flags: --puppeteer-debug
          # plugin_achievements_ignored: forker, follower, influencer, gister, worker, explorer, infographile
