name: Metrics Achivements
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
    inputs:
      commit_message:
        description: "Commit message"
        default: "chore: update metrics"
      git_user:
        description: "Git user"
        default: "Planxnx"
  push:
    paths:
      - ".github/workflows/metrics.achivements.yml"
env:
  COMMIT_EMAIL: planxthanee@gmail.com
  COMMIT_USER: Planxnx
  COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
  GIT_USER: ${{ github.event.inputs.git_user || 'Planxnx' }}

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    env:
      METRICS_DIR: "metrics"
      METRICS_FILE_NAME: "plugin.achivements.svg"

    steps:
      - name: Achivements Metrics
        uses: lowlighter/metrics@master # use @master to test new features, See more: https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md#3%EF%B8%8F1%EF%B8%8F-choosing-between-latest-mastermain-a-fork-or-a-pinned-version
        with:
          token: ${{ secrets.GH_TOKEN }}
          committer_token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.achivements.svg
          config_timezone: Asia/Bangkok
          user: ${{ env.GIT_USER }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          # plugin_achievements_ignored: forker, follower, influencer, gister, worker, explorer, infographile
