name: Metrics Main
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config user.name Planxnx
          git config user.email planxthanee@gmail.com

      - name: Main Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/main.svg
          config_timezone: Asia/Bangkok
          user: Planxnx
          template: classic
          base: header, activity, repositories
