name: Most Used Languages Metrics
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.language.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.languages.used.svg
          base: ""
          #Readmore: https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Thanee Charattrakool, Planxnx, planxnx@users.noreply.github.com, planxthanee@gmail.com
          plugin_languages_analysis_timeout: 30
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: no
          plugin_languages_categories: programming, markup
          plugin_languages_recent_categories: programming, markup
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, lines
          plugin_languages_ignored: hack
