name: Metrics Main
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.main.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Main Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/main.svg
          config_timezone: Asia/Bangkok
          user: Planxnx
          template: classic
          base: header, activity, repositories
          output_action: none

      - name: Commit Output
        run: |
          git config user.name Planxnx
          git config user.email planxthanee@gmail.com
          sudo mv /metrics_renders/* ./
          git add --all
          git commit -m "chore: push metrics"
          git push
