name: Metrics Habits
on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/metrics.habits.yml"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Interesting Facts Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.habits.facts.svg
          config_timezone: Asia/Bangkok
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_from: 1000
      - name: Activity Facts Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics/plugin.habits.charts.svg
          config_timezone: Asia/Bangkok
          base: ""
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          plugin_habits_trim: yes
