name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # every 6 hour

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.name "Planxnx"
          git config --global user.email "planxthanee@gmail.com"
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "feat(readme): update wakatime stats"
          SHOW_TITLE: true
          SHOW_TOTAL: false
          SHOW_TIME: false
          TIME_RANGE: last_30_days
